server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

elasticsearch:
  host: localhost
  port: 9200

logging:
  level:
    org:
      springframework: INFO