metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["es01:9200"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - uptime
      - socket_summary
      - core
      - diskio
      - socket
    process.include_top_n:
      by_cpu: 5      # include top 5 processes by CPU
      by_memory: 5   # include top 5 processes by memory
    cpu.metrics:  # The default is ["percentages"]
      - percentages

  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - event
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    processors:
      - add_docker_metadata: ~
